---
include:
  # reset 文件
  - board: nice_nano_v2
    shield: settings_reset

  - board: planck_left
    shield: nice_view_reverse
    snippet: studio-rpc-usb-uart

  - board: planck_right
    shield: nice_view_reverse
